apiVersion: v1
kind: Service
metadata:
  name: powerbi-service
spec:
  type: NodePort
  selector:
    app: powerbi
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30005 # Porta fixa para você acessar no navegador