# rules.py
categorization_rules = {
    'MERCADO': [r'RSHOP MERCADO ',r'RSHOP MARCO', r'RSHOP MUFFATO', r'SUPERMERCADO', r'RSHOP-MERCADO'],
    'FARMACIA': [r'FARMACIA', r'DROGARIA'],
    'SAQUE': [r'SAQUE', r'CXE'],
    'RESTAURANTE': [r'RSHOP-VIVENDA DO',r'RSHOP ESPETO',r'RESTAURANTE', r'PIZZARIA', r'RSHOP-ESPETO'],
    'TELEFONE': [r'TIM', r'VIVO', r'CLARO'],
    'INTERNET': [r'INTERNET', r'NET', r'CLARO'],
    'OUTROS': [r'EDUARDODIAS', r'MARIVANLIMA'],
    'GASOLINA': [r'RSHOP AUTO POSTO',r'RSHOP-AUTO POSTO'],
    'LUZ': [r'INT ELETROPAULO'],
    'GAS': [r'INT COMGAS']
    
}